<?php

namespace AppBundle\Repository;

use AppBundle\Model\RepositoryModel;

/**
 * CommentCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentCodeRepository extends RepositoryModel
{
    public function findComments(array $criteria)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->leftJoin('c.user', 'u')->addSelect('u');
        $qb->leftJoin('c.code', 'co')->addSelect('co');
        return $qb;
    }
}
