<?php

namespace AppBundle\Repository;

/**
 * CommentCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
