<?php

namespace AppBundle\Repository;

/**
 * CommentPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentPostRepository extends \Doctrine\ORM\EntityRepository
{
}
