<?php

namespace AppBundle\Repository;

use AppBundle\Model\RepositoryModel;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends RepositoryModel
{

    public function findLanguages(array $criteria)
    {
        $qb = $this->createQueryBuilder('l');

        return $qb;
    }

    public function getLanguagesStat()
    {
        return $this
                        ->createQueryBuilder('l')
                        ->leftJoin('l.codes', 'c')->addSelect('c')
                        ->groupBy('l.id')
                        ->select('l.id, l.name, COUNT(c.id) AS codeCount')
                        ->orderBy('l.name', 'ASC')
                        ->getQuery()->getArrayResult();
    }

}
