<?php

namespace AppBundle\Repository;

use AppBundle\Model\RepositoryModel;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends RepositoryModel
{

    public function findLanguages(array $criteria)
    {
        $qb = $this->createQueryBuilder('l');

        return $qb;
    }

}
