<?php

namespace AppBundle\Repository;

use AppBundle\Model\RepositoryModel;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends RepositoryModel
{

    /**
     * 
     * @param array $criteria
     * 
     * @return QueryBuilder
     */
    public function findPosts(array $criteria)
    {
        $qb = $this->createQueryBuilder('p');

        $qb->leftJoin('p.user', 'u')->addSelect('u');
        $qb->leftJoin('p.tags', 't')->addSelect('t');

        $itag = 1;
        foreach ($criteria['tags'] as $tag) {
            $qb->andWhere($qb->expr()->like('t.name', ':tag' . $itag));
            $qb->setParameter('tag' . $itag, $tag);
            $itag++;
        }
        return $qb;
    }

    /**
     * Get entity with related entities
     * 
     * @param int $id
     * 
     * @return null|QueryBuilder
     */
    public function findShow($id)
    {
        $qb = $this->createQueryBuilder('p');
        $qb
                ->leftJoin('p.user', 'u')->addSelect('u')
                ->leftJoin('p.tags', 't')->addSelect('t')
                ->where($qb->expr()->eq('p.id', ':id'))
                ->setParameter('id', $id)
        ;
        return $qb->getQuery()->getOneOrNullResult();
    }

}
