<?php

namespace AppBundle\Repository;

/**
 * SkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillRepository extends \Doctrine\ORM\EntityRepository
{

    public function findSkills(array $criteria)
    {
        $qb = $this->createQueryBuilder('s');
        
        return $qb->getQuery()->getResult();
    }

}
