<?php

namespace AppBundle\Repository;

use AppBundle\Model\RepositoryModel;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends RepositoryModel
{

    /**
     * Find tags entities filtered by criteria
     * 
     * @param array $criteria
     * 
     * @return QueryBuilder
     */
    public function findTags(array $criteria)
    {
        $qb = $this->createQueryBuilder('t');

        return $qb;
    }

}
