<?php

namespace AppBundle\Repository;

use AppBundle\Model\RepositoryModel;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends RepositoryModel
{

    public function findUsers(array $criteria, $isAdmin)
    {
        $qb = $this->createQueryBuilder('u');
        
        $qb->leftJoin('u.skills', 's')->addSelect('s');
        
        if(false === $isAdmin){
            $qb->andWhere($qb->expr()->isNull('u.status'));
        }
        return $qb;
    }

}
