fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin:
    resource: "@AdminBundle/Controller/"
    type: annotation   
 