parameters:
    
    
services:
    
    user.manager:
        class: AppBundle\Manager\UserManager
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@knp_paginator'
