<?php

namespace AppBundle\DataFixtures\ORM;

use AppBundle\Entity\Language;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;

/**
 * Description of LanguageFixtures
 *
 * @author linkus
 */
class LanguageFixtures extends Fixture
{

    public function load(ObjectManager $manager)
    {
        $data = [
            'abap',
            'abc',
            'actionscript',
            'ada',
            'apache_conf',
            'applescript',
            'asciidoc',
            'assembly_x86',
            'autohotkeys',
            'batchfile',
            'behaviour',
            'bro',
            'c9search',
            'c_cpp',
            'clojure',
            'cobol',
            'coffee',
            'coldfusion',
            'csharp',
            'css',
            'curly',
            'd',
            'dart',
            'diff',
            'django',
            'dockerfile',
            'dot',
            'drools',
            'eiffel',
            'elixir',
            'elm',
            'erlang',
            'forth',
            'fortran',
            'ftl',
            'gcode',
            'gherkin',
            'gitignore',
            'glsl',
            'gobstones',
            'golang',
            'graphqlschema',
            'groovy',
            'haml',
            'handlebars',
            'haskell',
            'haskell_cabal',
            'haxe',
            'hjson',
            'html',
            'html_elixir',
            'html_ruby',
            'ini',
            'io',
            'jack',
            'jade',
            'java',
            'javascript',
            'json',
            'jsoniq',
            'jsp',
            'jsx',
            'julia',
            'kotlin',
            'latex',
            'less',
            'liquid',
            'lisp',
            'livescript',
            'logiql',
            'lsl',
            'lua',
            'luapage',
            'lucene',
            'makefile',
            'markdown',
            'mask',
            'matlab',
            'maze',
            'mel',
            'mushcode',
            'mysql',
            'nix',
            'objectivec',
            'ocaml',
            'pascal',
            'perl',
            'pgsql',
            'php',
            'pig',
            'plain_text',
            'powershell',
            'praat',
            'prolog',
            'properties',
            'protobuf',
            'python',
            'r',
            'razor',
            'rdoc',
            'rhtml',
            'rst',
            'ruby',
            'rust',
            'sass',
            'scad',
            'scala',
            'scheme',
            'scss',
            'sh',
            'sjs',
            'smarty',
            'snippet',
            'soy_template',
            'space',
            'sparql',
            'sql',
            'sqlserver',
            'stylus',
            'svg',
            'swift',
            'tcl',
            'tex',
            'text',
            'textile',
            'toml',
            'tsx',
            'turtle',
            'twig',
            'typescipt',
            'vala',
            'vbscript',
            'velocity',
            'verilog',
            'vhdl',
            'wollock',
            'xml',
            'xquery',
            'yaml',
        ];

        foreach ($data as $name) {
            $lang = new Language;
            $lang->setName($name);
            $manager->persist($lang);
        }

        $manager->flush();
    }

}
