AppBundle\Entity\Code:
    type: entity
    table: code
    repositoryClass: AppBundle\Repository\CodeRepository
    lifecycleCallbacks: {  }
    id: { id: { type: integer, id: true, generator: { strategy: AUTO }}}
    
    fields:
        title:          { type: string,     length: 65 }
        description:    { type: string,     length: 200,  nullable: true }
        content:        { type: string,     length: 1200  }
        createdAt:      { type: datetime }
        updatedAt:      { type: datetime,                 nullable: true }
    
    oneToOne:
        language:
            targetEntity: AppBundle\Entity\Language
            joinColumn:
                name: language_id
                referencedColumnName: id
    
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User 
            joinColumn:
                name: user_id
                referencedColumnName: id
                
    manyToMany:
        tags:
            targetEntity: AppBundle\Entity\Tag
            joinTable:
                name: tags_codes
                joinColumns:
                    code_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: CASCADE
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: CASCADE
                
    