AppBundle\Entity\CommentCode:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CommentCodeRepository
    lifecycleCallbacks:
        prePersist: [ insertDate ]
        
    id: { id: { type: integer, id: true, generator: { strategy: AUTO }}}
    
    fields:
        content:        { type: string,     length: 600  }
        createdAt:      { type: datetime }
        updatedAt:      { type: datetime,   nullable: true }
        
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User 
            joinColumn:
                name: user_id
                nullable: false
                referencedColumnName: id
        code:
            targetEntity: AppBundle\Entity\Code
            joinColumn:
                name: code_id
                nullable: false
                referencedColumnName: id
