AppBundle\Entity\Language:
    type: entity
    table: programming_languages
    repositoryClass: AppBundle\Repository\LanguageRepository
    lifecycleCallbacks: {  }
    
    id: { id: { type: integer, id: true, generator: { strategy: AUTO }}}
    
    fields:
        name:   { type: string,     length: 65,  unique: true }
        count:  { type: integer,    nullable: true }
        
    oneToMany:
        codes:
            targetEntity: AppBundle\Entity\Code
            mappedBy: language
            
