AppBundle\Entity\Theme:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ThemeRepository
    id: { id: { type: integer, id: true, generator: { strategy: AUTO }}}
    
    fields:
        name:   { type: string,     length: 65,  unique: true }
