AppBundle\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass: AppBundle\Repository\UserRepository
    lifecycleCallbacks:
        prePersist: [ insertDate ]
    
    
    id: { id: { type: integer, id: true, generator: { strategy: AUTO }}}
    
    fields:
        firstname:  { type: string,     length: 65,    nullable: true }
        lastname:   { type: string,     length: 65,    nullable: true }
        job:        { type: json_array,                nullable: true }
        bio:        { type: string,     length: 1000,  nullable: true }
        createdAt:  { type: datetime }
        updatedAt:  { type: datetime,                  nullable: true }
        img:        { type: string,     length: 10,    nullable: true }
        status:     { type: boolean,                   nullable: true }
    
    oneToOne:
        theme:
            targetEntity: AppBundle\Entity\Theme
            joinColumn:
                name: theme_id
                nullable: true
                referencedColumnName: id
    manyToMany:
        skills:
            targetEntity: AppBundle\Entity\Skill
            joinTable:
                name: users_skills
                joinColumns:
                    user_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: CASCADE
                inverseJoinColumns:
                    skill_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: RESTRICT
        favCode:
            targetEntity: AppBundle\Entity\Code
            joinTable:
                name: fav_codes
                joinColumns:
                    user_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: CASCADE
                inverseJoinColumns:
                    code_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: RESTRICT
        favPost:
            targetEntity: AppBundle\Entity\Post
            joinTable:
                name: fav_posts
                joinColumns:
                    user_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: CASCADE
                inverseJoinColumns:
                    post_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: RESTRICT