AppBundle\Entity\Tag:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name]
            message: This tag is already in the database;
    properties:
        name:
            - NotBlank:
                groups: [single]
            - Length:
                groups: [single]
                min: 1
                max: 20
                minMessage: 'tag must be at least {{ limit }} characters long'
                maxMessage: 'tag cannot be longer than {{ limit }} characters'
            - Regex:
                groups: [single]
                pattern: '/^[-a-z0-9 ]{1,20}$/'
                match:   true
                message: Your name need to match pattern {{ patern }}
            - Regex:
                groups: [multiple]
                pattern: '/^[-a-z0-9 ]{1,20}$/'
                match:   true
                message: Your name need to match pattern {{ patern }}
            
            
   